package logic.pokemua;

import logic.skill.Skill;
import logic.skill.SkillTemplate;

import java.util.ArrayList;

public class PokemuaLoader {

    /**
     * Size of all pokemuas
     */
    public static final int SIZE = 151;

    /**
     * List of all pokemuas
     */
    private static final PokemuaTemplate[] pokemuasData = {
            new PokemuaTemplate(0, "", 0, 0, 0, ""),
            new PokemuaTemplate(1, "Bulbasaur", 45, 49, 49, "file:asset/pokemua/0001.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(13, 1), new PokemuaTemplate.SkillEntry(27, 2), new PokemuaTemplate.SkillEntry(48, 3)}),
            new PokemuaTemplate(2, "Ivysaur", 60, 62, 63, "file:asset/pokemua/0002.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(13, 1), new PokemuaTemplate.SkillEntry(30, 2), new PokemuaTemplate.SkillEntry(54, 3)}),
            new PokemuaTemplate(3, "Venusaur", 80, 82, 83, "file:asset/pokemua/0003.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(1, 1), new PokemuaTemplate.SkillEntry(13, 1), new PokemuaTemplate.SkillEntry(30, 2), new PokemuaTemplate.SkillEntry(65, 3)}),
            new PokemuaTemplate(4, "Charmander", 39, 52, 43, "file:asset/pokemua/0004.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(9, 5), new PokemuaTemplate.SkillEntry(22, 6), new PokemuaTemplate.SkillEntry(30, 7), new PokemuaTemplate.SkillEntry(38, 8), new PokemuaTemplate.SkillEntry(46, 9)}),
            new PokemuaTemplate(5, "Charmeleon", 58, 64, 58, "file:asset/pokemua/0005.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 5), new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(9, 5), new PokemuaTemplate.SkillEntry(24, 6), new PokemuaTemplate.SkillEntry(33, 7), new PokemuaTemplate.SkillEntry(42, 8), new PokemuaTemplate.SkillEntry(56, 9)}),
            new PokemuaTemplate(6, "Charizard", 78, 84, 78, "file:asset/pokemua/0006.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 5), new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(9, 5), new PokemuaTemplate.SkillEntry(24, 6), new PokemuaTemplate.SkillEntry(36, 7), new PokemuaTemplate.SkillEntry(46, 8), new PokemuaTemplate.SkillEntry(55, 9)}),
            new PokemuaTemplate(7, "Squirtle", 44, 48, 65, "file:asset/pokemua/0007.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(8, 10), new PokemuaTemplate.SkillEntry(15, 11), new PokemuaTemplate.SkillEntry(22, 12), new PokemuaTemplate.SkillEntry(35, 13), new PokemuaTemplate.SkillEntry(42, 14)}),
            new PokemuaTemplate(8, "Wartortle", 59, 63, 80, "file:asset/pokemua/0008.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 10), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(8, 10), new PokemuaTemplate.SkillEntry(15, 11), new PokemuaTemplate.SkillEntry(24, 12), new PokemuaTemplate.SkillEntry(39, 13), new PokemuaTemplate.SkillEntry(47, 14)}),
            new PokemuaTemplate(9, "Blastoise", 79, 83, 100, "file:asset/pokemua/0009.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 10), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(1, 11), new PokemuaTemplate.SkillEntry(8, 10), new PokemuaTemplate.SkillEntry(15, 11), new PokemuaTemplate.SkillEntry(24, 12), new PokemuaTemplate.SkillEntry(42, 13), new PokemuaTemplate.SkillEntry(52, 14)}),
            new PokemuaTemplate(10, "Caterpie", 45, 30, 35, "file:asset/pokemua/0010.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0)}),
            new PokemuaTemplate(11, "Metapod", 50, 20, 55, "file:asset/pokemua/0011.png", new PokemuaTemplate.SkillEntry[]{}),
            new PokemuaTemplate(12, "Butterfree", 60, 45, 50, "file:asset/pokemua/0012.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 15), new PokemuaTemplate.SkillEntry(12, 15), new PokemuaTemplate.SkillEntry(32, 16)}),
            new PokemuaTemplate(13, "Weedle", 40, 35, 30, "file:asset/pokemua/0013.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 17)}),
            new PokemuaTemplate(14, "Kakuna", 45, 25, 50, "file:asset/pokemua/0014.png", new PokemuaTemplate.SkillEntry[]{}),
            new PokemuaTemplate(15, "Beedrill", 65, 90, 40, "file:asset/pokemua/0015.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 18), new PokemuaTemplate.SkillEntry(12, 18), new PokemuaTemplate.SkillEntry(20, 19), new PokemuaTemplate.SkillEntry(25, 6), new PokemuaTemplate.SkillEntry(30, 20)}),
            new PokemuaTemplate(16, "Pidgey", 40, 45, 40, "file:asset/pokemua/0016.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 21), new PokemuaTemplate.SkillEntry(12, 22), new PokemuaTemplate.SkillEntry(28, 23)}),
            new PokemuaTemplate(17, "Pidgeotto", 63, 60, 55, "file:asset/pokemua/0017.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 21), new PokemuaTemplate.SkillEntry(12, 22), new PokemuaTemplate.SkillEntry(31, 23)}),
            new PokemuaTemplate(18, "Pidgeot", 83, 80, 75, "file:asset/pokemua/0018.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 21), new PokemuaTemplate.SkillEntry(1, 22), new PokemuaTemplate.SkillEntry(12, 22), new PokemuaTemplate.SkillEntry(31, 23)}),
            new PokemuaTemplate(19, "Rattata", 30, 56, 35, "file:asset/pokemua/0019.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(7, 22), new PokemuaTemplate.SkillEntry(14, 24), new PokemuaTemplate.SkillEntry(34, 25)}),
            new PokemuaTemplate(20, "Raticate", 55, 81, 60, "file:asset/pokemua/0020.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 22), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(7, 22), new PokemuaTemplate.SkillEntry(14, 24), new PokemuaTemplate.SkillEntry(41, 25)}),
            new PokemuaTemplate(21, "Spearow", 40, 60, 30, "file:asset/pokemua/0021.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 26), new PokemuaTemplate.SkillEntry(15, 18), new PokemuaTemplate.SkillEntry(29, 27)}),
            new PokemuaTemplate(22, "Fearow", 65, 90, 65, "file:asset/pokemua/0022.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 26), new PokemuaTemplate.SkillEntry(15, 18), new PokemuaTemplate.SkillEntry(34, 27)}),
            new PokemuaTemplate(23, "Ekans", 35, 60, 44, "file:asset/pokemua/0023.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 28), new PokemuaTemplate.SkillEntry(10, 17), new PokemuaTemplate.SkillEntry(17, 12), new PokemuaTemplate.SkillEntry(38, 29)}),
            new PokemuaTemplate(24, "Arbok", 60, 95, 69, "file:asset/pokemua/0024.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 17), new PokemuaTemplate.SkillEntry(1, 28), new PokemuaTemplate.SkillEntry(10, 17), new PokemuaTemplate.SkillEntry(17, 12), new PokemuaTemplate.SkillEntry(47, 29)}),
            new PokemuaTemplate(25, "Pikachu", 35, 55, 40, "file:asset/pokemua/0025.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 30), new PokemuaTemplate.SkillEntry(16, 22), new PokemuaTemplate.SkillEntry(26, 31), new PokemuaTemplate.SkillEntry(43, 32)}),
            new PokemuaTemplate(26, "Raichu", 60, 90, 55, "file:asset/pokemua/0026.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 30)}),
            new PokemuaTemplate(27, "Sandshrew", 50, 75, 85, "file:asset/pokemua/0027.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(17, 7), new PokemuaTemplate.SkillEntry(24, 17), new PokemuaTemplate.SkillEntry(31, 31), new PokemuaTemplate.SkillEntry(38, 33)}),
            new PokemuaTemplate(28, "Sandslash", 75, 100, 110, "file:asset/pokemua/0028.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(17, 7), new PokemuaTemplate.SkillEntry(27, 17), new PokemuaTemplate.SkillEntry(36, 31), new PokemuaTemplate.SkillEntry(47, 33)}),
            new PokemuaTemplate(29, "Nidoran♀ (female)", 55, 47, 52, "file:asset/pokemua/0029.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(8, 4), new PokemuaTemplate.SkillEntry(14, 17), new PokemuaTemplate.SkillEntry(29, 12), new PokemuaTemplate.SkillEntry(36, 33), new PokemuaTemplate.SkillEntry(43, 34)}),
            new PokemuaTemplate(30, "Nidorina", 70, 62, 67, "file:asset/pokemua/0030.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(8, 4), new PokemuaTemplate.SkillEntry(14, 17), new PokemuaTemplate.SkillEntry(32, 12), new PokemuaTemplate.SkillEntry(41, 33), new PokemuaTemplate.SkillEntry(50, 34)}),
            new PokemuaTemplate(31, "Nidoqueen", 90, 92, 87, "file:asset/pokemua/0031.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 35), new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(8, 4), new PokemuaTemplate.SkillEntry(14, 17), new PokemuaTemplate.SkillEntry(23, 35)}),
            new PokemuaTemplate(32, "Nidoran♂ (male)", 46, 57, 40, "file:asset/pokemua/0032.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(8, 36), new PokemuaTemplate.SkillEntry(14, 17), new PokemuaTemplate.SkillEntry(29, 18), new PokemuaTemplate.SkillEntry(36, 37), new PokemuaTemplate.SkillEntry(43, 34)}),
            new PokemuaTemplate(33, "Nidorino", 61, 72, 57, "file:asset/pokemua/0033.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 36), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(8, 36), new PokemuaTemplate.SkillEntry(14, 17), new PokemuaTemplate.SkillEntry(32, 18), new PokemuaTemplate.SkillEntry(41, 37), new PokemuaTemplate.SkillEntry(50, 34)}),
            new PokemuaTemplate(34, "Nidoking", 81, 102, 77, "file:asset/pokemua/0034.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 36), new PokemuaTemplate.SkillEntry(1, 17), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(1, 38), new PokemuaTemplate.SkillEntry(8, 36), new PokemuaTemplate.SkillEntry(14, 17), new PokemuaTemplate.SkillEntry(23, 38)}),
            new PokemuaTemplate(35, "Clefairy", 70, 45, 48, "file:asset/pokemua/0035.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 39), new PokemuaTemplate.SkillEntry(18, 40)}),
            new PokemuaTemplate(36, "Clefable", 95, 70, 73, "file:asset/pokemua/0036.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 40)}),
            new PokemuaTemplate(37, "Vulpix", 38, 41, 40, "file:asset/pokemua/0037.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 5), new PokemuaTemplate.SkillEntry(16, 22), new PokemuaTemplate.SkillEntry(35, 8), new PokemuaTemplate.SkillEntry(42, 9)}),
            new PokemuaTemplate(38, "Ninetales", 73, 76, 75, "file:asset/pokemua/0038.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 5), new PokemuaTemplate.SkillEntry(1, 22)}),
            new PokemuaTemplate(39, "Jigglypuff", 115, 45, 20, "file:asset/pokemua/0039.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(9, 39), new PokemuaTemplate.SkillEntry(24, 40), new PokemuaTemplate.SkillEntry(34, 35), new PokemuaTemplate.SkillEntry(39, 41)}),
            new PokemuaTemplate(40, "Wigglytuff", 140, 70, 45, "file:asset/pokemua/0040.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 40)}),
            new PokemuaTemplate(41, "Zubat", 40, 45, 35, "file:asset/pokemua/0041.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 42), new PokemuaTemplate.SkillEntry(15, 12), new PokemuaTemplate.SkillEntry(28, 23)}),
            new PokemuaTemplate(42, "Golbat", 75, 80, 70, "file:asset/pokemua/0042.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 12), new PokemuaTemplate.SkillEntry(1, 42), new PokemuaTemplate.SkillEntry(15, 12), new PokemuaTemplate.SkillEntry(32, 23)}),
            new PokemuaTemplate(43, "Oddish", 45, 50, 55, "file:asset/pokemua/0043.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 43), new PokemuaTemplate.SkillEntry(24, 29), new PokemuaTemplate.SkillEntry(33, 44), new PokemuaTemplate.SkillEntry(46, 3)}),
            new PokemuaTemplate(44, "Gloom", 60, 65, 70, "file:asset/pokemua/0044.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 43), new PokemuaTemplate.SkillEntry(28, 29), new PokemuaTemplate.SkillEntry(38, 44), new PokemuaTemplate.SkillEntry(52, 3)}),
            new PokemuaTemplate(45, "Vileplume", 75, 80, 85, "file:asset/pokemua/0045.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 29), new PokemuaTemplate.SkillEntry(1, 44)}),
            new PokemuaTemplate(46, "Paras", 35, 70, 55, "file:asset/pokemua/0046.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(20, 42), new PokemuaTemplate.SkillEntry(34, 7)}),
            new PokemuaTemplate(47, "Parasect", 60, 95, 80, "file:asset/pokemua/0047.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 42), new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(20, 42), new PokemuaTemplate.SkillEntry(39, 7)}),
            new PokemuaTemplate(48, "Venonat", 60, 55, 50, "file:asset/pokemua/0048.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(27, 42), new PokemuaTemplate.SkillEntry(35, 16), new PokemuaTemplate.SkillEntry(43, 45)}),
            new PokemuaTemplate(49, "Venomoth", 70, 65, 60, "file:asset/pokemua/0049.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 42), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(27, 42), new PokemuaTemplate.SkillEntry(38, 16), new PokemuaTemplate.SkillEntry(50, 45)}),
            new PokemuaTemplate(50, "Diglett", 10, 55, 25, "file:asset/pokemua/0050.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(19, 46), new PokemuaTemplate.SkillEntry(31, 7), new PokemuaTemplate.SkillEntry(40, 47)}),
            new PokemuaTemplate(51, "Dugtrio", 35, 100, 50, "file:asset/pokemua/0051.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 46), new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(19, 46), new PokemuaTemplate.SkillEntry(35, 7), new PokemuaTemplate.SkillEntry(47, 47)}),
            new PokemuaTemplate(52, "Meowth", 40, 45, 35, "file:asset/pokemua/0052.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(12, 12), new PokemuaTemplate.SkillEntry(17, 48), new PokemuaTemplate.SkillEntry(33, 33), new PokemuaTemplate.SkillEntry(44, 7)}),
            new PokemuaTemplate(53, "Persian", 65, 70, 60, "file:asset/pokemua/0053.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 12), new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(12, 12), new PokemuaTemplate.SkillEntry(17, 48), new PokemuaTemplate.SkillEntry(37, 33), new PokemuaTemplate.SkillEntry(51, 7)}),
            new PokemuaTemplate(54, "Psyduck", 50, 52, 48, "file:asset/pokemua/0054.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(36, 15), new PokemuaTemplate.SkillEntry(43, 33), new PokemuaTemplate.SkillEntry(52, 14)}),
            new PokemuaTemplate(55, "Golduck", 80, 82, 78, "file:asset/pokemua/0055.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(39, 15), new PokemuaTemplate.SkillEntry(48, 33), new PokemuaTemplate.SkillEntry(59, 14)}),
            new PokemuaTemplate(56, "Mankey", 40, 80, 35, "file:asset/pokemua/0056.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(15, 49), new PokemuaTemplate.SkillEntry(21, 33), new PokemuaTemplate.SkillEntry(33, 50), new PokemuaTemplate.SkillEntry(39, 38)}),
            new PokemuaTemplate(57, "Primeape", 65, 105, 60, "file:asset/pokemua/0057.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 33), new PokemuaTemplate.SkillEntry(1, 49), new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(15, 49), new PokemuaTemplate.SkillEntry(21, 33), new PokemuaTemplate.SkillEntry(37, 50), new PokemuaTemplate.SkillEntry(46, 38)}),
            new PokemuaTemplate(58, "Growlithe", 55, 70, 45, "file:asset/pokemua/0058.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 12), new PokemuaTemplate.SkillEntry(18, 5), new PokemuaTemplate.SkillEntry(30, 51), new PokemuaTemplate.SkillEntry(50, 8)}),
            new PokemuaTemplate(59, "Arcanine", 90, 110, 80, "file:asset/pokemua/0059.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 5), new PokemuaTemplate.SkillEntry(1, 51)}),
            new PokemuaTemplate(60, "Poliwag", 40, 50, 40, "file:asset/pokemua/0060.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 10), new PokemuaTemplate.SkillEntry(19, 11), new PokemuaTemplate.SkillEntry(25, 40), new PokemuaTemplate.SkillEntry(31, 35), new PokemuaTemplate.SkillEntry(45, 14)}),
            new PokemuaTemplate(61, "Poliwhirl", 65, 65, 65, "file:asset/pokemua/0061.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 10), new PokemuaTemplate.SkillEntry(1, 11), new PokemuaTemplate.SkillEntry(19, 11), new PokemuaTemplate.SkillEntry(26, 40), new PokemuaTemplate.SkillEntry(33, 35), new PokemuaTemplate.SkillEntry(49, 14)}),
            new PokemuaTemplate(62, "Poliwrath", 90, 95, 95, "file:asset/pokemua/0062.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 35), new PokemuaTemplate.SkillEntry(1, 40), new PokemuaTemplate.SkillEntry(1, 11), new PokemuaTemplate.SkillEntry(19, 11)}),
            new PokemuaTemplate(63, "Abra", 25, 20, 15, "file:asset/pokemua/0063.png", new PokemuaTemplate.SkillEntry[]{}),
            new PokemuaTemplate(64, "Kadabra", 40, 35, 30, "file:asset/pokemua/0064.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 15), new PokemuaTemplate.SkillEntry(16, 15), new PokemuaTemplate.SkillEntry(27, 16), new PokemuaTemplate.SkillEntry(38, 45)}),
            new PokemuaTemplate(65, "Alakazam", 55, 50, 45, "file:asset/pokemua/0065.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 15), new PokemuaTemplate.SkillEntry(16, 15), new PokemuaTemplate.SkillEntry(27, 16), new PokemuaTemplate.SkillEntry(38, 45)}),
            new PokemuaTemplate(66, "Machop", 70, 80, 50, "file:asset/pokemua/0066.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 49), new PokemuaTemplate.SkillEntry(20, 52), new PokemuaTemplate.SkillEntry(39, 50), new PokemuaTemplate.SkillEntry(46, 53)}),
            new PokemuaTemplate(67, "Machoke", 80, 100, 70, "file:asset/pokemua/0067.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 49), new PokemuaTemplate.SkillEntry(1, 52), new PokemuaTemplate.SkillEntry(20, 52), new PokemuaTemplate.SkillEntry(44, 50), new PokemuaTemplate.SkillEntry(52, 53)}),
            new PokemuaTemplate(68, "Machamp", 90, 130, 80, "file:asset/pokemua/0068.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 49), new PokemuaTemplate.SkillEntry(1, 52), new PokemuaTemplate.SkillEntry(20, 52), new PokemuaTemplate.SkillEntry(44, 50), new PokemuaTemplate.SkillEntry(52, 53)}),
            new PokemuaTemplate(69, "Bellsprout", 50, 75, 35, "file:asset/pokemua/0069.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 1), new PokemuaTemplate.SkillEntry(13, 28), new PokemuaTemplate.SkillEntry(26, 29), new PokemuaTemplate.SkillEntry(33, 2), new PokemuaTemplate.SkillEntry(42, 54)}),
            new PokemuaTemplate(70, "Weepinbell", 65, 90, 50, "file:asset/pokemua/0070.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 1), new PokemuaTemplate.SkillEntry(1, 28), new PokemuaTemplate.SkillEntry(13, 28), new PokemuaTemplate.SkillEntry(29, 29), new PokemuaTemplate.SkillEntry(38, 2), new PokemuaTemplate.SkillEntry(49, 54)}),
            new PokemuaTemplate(71, "Victreebel", 80, 105, 65, "file:asset/pokemua/0071.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 29), new PokemuaTemplate.SkillEntry(1, 2), new PokemuaTemplate.SkillEntry(13, 28)}),
            new PokemuaTemplate(72, "Tentacool", 40, 40, 35, "file:asset/pokemua/0072.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 29), new PokemuaTemplate.SkillEntry(13, 28), new PokemuaTemplate.SkillEntry(18, 17), new PokemuaTemplate.SkillEntry(22, 11), new PokemuaTemplate.SkillEntry(27, 55), new PokemuaTemplate.SkillEntry(48, 14)}),
            new PokemuaTemplate(73, "Tentacruel", 80, 70, 65, "file:asset/pokemua/0073.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 29), new PokemuaTemplate.SkillEntry(1, 28), new PokemuaTemplate.SkillEntry(13, 28), new PokemuaTemplate.SkillEntry(18, 17), new PokemuaTemplate.SkillEntry(22, 11), new PokemuaTemplate.SkillEntry(27, 55), new PokemuaTemplate.SkillEntry(50, 14)}),
            new PokemuaTemplate(74, "Geodude", 40, 80, 100, "file:asset/pokemua/0074.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(16, 56), new PokemuaTemplate.SkillEntry(21, 57), new PokemuaTemplate.SkillEntry(31, 47), new PokemuaTemplate.SkillEntry(36, 58)}),
            new PokemuaTemplate(75, "Graveler", 55, 95, 115, "file:asset/pokemua/0075.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(16, 56), new PokemuaTemplate.SkillEntry(21, 57), new PokemuaTemplate.SkillEntry(36, 47), new PokemuaTemplate.SkillEntry(43, 58)}),
            new PokemuaTemplate(76, "Golem", 80, 120, 130, "file:asset/pokemua/0076.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(16, 56), new PokemuaTemplate.SkillEntry(21, 57), new PokemuaTemplate.SkillEntry(36, 47), new PokemuaTemplate.SkillEntry(43, 58)}),
            new PokemuaTemplate(77, "Ponyta", 50, 85, 55, "file:asset/pokemua/0077.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 5), new PokemuaTemplate.SkillEntry(32, 59), new PokemuaTemplate.SkillEntry(39, 9), new PokemuaTemplate.SkillEntry(43, 51)}),
            new PokemuaTemplate(78, "Rapidash", 65, 100, 70, "file:asset/pokemua/0078.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 5), new PokemuaTemplate.SkillEntry(1, 59), new PokemuaTemplate.SkillEntry(32, 59), new PokemuaTemplate.SkillEntry(39, 9), new PokemuaTemplate.SkillEntry(47, 51)}),
            new PokemuaTemplate(79, "Slowpoke", 90, 65, 65, "file:asset/pokemua/0079.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 15), new PokemuaTemplate.SkillEntry(22, 60), new PokemuaTemplate.SkillEntry(33, 11), new PokemuaTemplate.SkillEntry(48, 45)}),
            new PokemuaTemplate(80, "Slowbro", 95, 75, 110, "file:asset/pokemua/0080.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 15), new PokemuaTemplate.SkillEntry(1, 60), new PokemuaTemplate.SkillEntry(22, 60), new PokemuaTemplate.SkillEntry(33, 11), new PokemuaTemplate.SkillEntry(55, 45)}),
            new PokemuaTemplate(81, "Magnemite", 25, 35, 70, "file:asset/pokemua/0081.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(21, 61), new PokemuaTemplate.SkillEntry(25, 30), new PokemuaTemplate.SkillEntry(41, 31)}),
            new PokemuaTemplate(82, "Magneton", 50, 60, 95, "file:asset/pokemua/0082.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 61), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(1, 30), new PokemuaTemplate.SkillEntry(21, 61), new PokemuaTemplate.SkillEntry(25, 30), new PokemuaTemplate.SkillEntry(46, 31)}),
            new PokemuaTemplate(83, "Farfetch'd", 52, 90, 55, "file:asset/pokemua/0083.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 26), new PokemuaTemplate.SkillEntry(15, 18), new PokemuaTemplate.SkillEntry(39, 7)}),
            new PokemuaTemplate(84, "Doduo", 35, 85, 45, "file:asset/pokemua/0084.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 26), new PokemuaTemplate.SkillEntry(24, 18), new PokemuaTemplate.SkillEntry(30, 27), new PokemuaTemplate.SkillEntry(36, 6), new PokemuaTemplate.SkillEntry(40, 62)}),
            new PokemuaTemplate(85, "Dodrio", 60, 110, 70, "file:asset/pokemua/0085.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 18), new PokemuaTemplate.SkillEntry(1, 26), new PokemuaTemplate.SkillEntry(24, 18), new PokemuaTemplate.SkillEntry(30, 27), new PokemuaTemplate.SkillEntry(39, 6), new PokemuaTemplate.SkillEntry(45, 62)}),
            new PokemuaTemplate(86, "Seel", 65, 45, 55, "file:asset/pokemua/0086.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 60), new PokemuaTemplate.SkillEntry(35, 63), new PokemuaTemplate.SkillEntry(45, 51), new PokemuaTemplate.SkillEntry(50, 64)}),
            new PokemuaTemplate(87, "Dewgong", 90, 70, 80, "file:asset/pokemua/0087.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 63), new PokemuaTemplate.SkillEntry(1, 60), new PokemuaTemplate.SkillEntry(35, 63), new PokemuaTemplate.SkillEntry(50, 51), new PokemuaTemplate.SkillEntry(56, 64)}),
            new PokemuaTemplate(88, "Grimer", 80, 80, 50, "file:asset/pokemua/0088.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 39), new PokemuaTemplate.SkillEntry(37, 65)}),
            new PokemuaTemplate(89, "Muk", 105, 105, 75, "file:asset/pokemua/0089.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 39), new PokemuaTemplate.SkillEntry(37, 65)}),
            new PokemuaTemplate(90, "Shellder", 30, 65, 100, "file:asset/pokemua/0090.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(23, 66), new PokemuaTemplate.SkillEntry(30, 63), new PokemuaTemplate.SkillEntry(50, 64)}),
            new PokemuaTemplate(91, "Cloyster", 50, 95, 180, "file:asset/pokemua/0091.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 63), new PokemuaTemplate.SkillEntry(1, 66), new PokemuaTemplate.SkillEntry(50, 67)}),
            new PokemuaTemplate(92, "Gastly", 30, 35, 30, "file:asset/pokemua/0092.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 68), new PokemuaTemplate.SkillEntry(1, 69), new PokemuaTemplate.SkillEntry(35, 70)}),
            new PokemuaTemplate(93, "Haunter", 45, 50, 45, "file:asset/pokemua/0093.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 68), new PokemuaTemplate.SkillEntry(1, 69), new PokemuaTemplate.SkillEntry(38, 70)}),
            new PokemuaTemplate(94, "Gengar", 60, 65, 60, "file:asset/pokemua/0094.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 68), new PokemuaTemplate.SkillEntry(1, 69), new PokemuaTemplate.SkillEntry(38, 70)}),
            new PokemuaTemplate(95, "Onix", 35, 45, 160, "file:asset/pokemua/0095.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(15, 71), new PokemuaTemplate.SkillEntry(19, 56), new PokemuaTemplate.SkillEntry(25, 6), new PokemuaTemplate.SkillEntry(33, 54)}),
            new PokemuaTemplate(96, "Drowzee", 60, 48, 45, "file:asset/pokemua/0096.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 39), new PokemuaTemplate.SkillEntry(17, 15), new PokemuaTemplate.SkillEntry(24, 60), new PokemuaTemplate.SkillEntry(32, 45)}),
            new PokemuaTemplate(97, "Hypno", 85, 73, 70, "file:asset/pokemua/0097.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 15), new PokemuaTemplate.SkillEntry(1, 39), new PokemuaTemplate.SkillEntry(17, 15), new PokemuaTemplate.SkillEntry(24, 60), new PokemuaTemplate.SkillEntry(37, 45)}),
            new PokemuaTemplate(98, "Krabby", 30, 105, 90, "file:asset/pokemua/0098.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 10), new PokemuaTemplate.SkillEntry(20, 72), new PokemuaTemplate.SkillEntry(25, 73), new PokemuaTemplate.SkillEntry(30, 59), new PokemuaTemplate.SkillEntry(35, 74)}),
            new PokemuaTemplate(99, "Kingler", 55, 130, 115, "file:asset/pokemua/0099.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 10), new PokemuaTemplate.SkillEntry(1, 72), new PokemuaTemplate.SkillEntry(20, 72), new PokemuaTemplate.SkillEntry(25, 73), new PokemuaTemplate.SkillEntry(34, 59), new PokemuaTemplate.SkillEntry(42, 74)}),
            new PokemuaTemplate(100, "Voltorb", 40, 30, 50, "file:asset/pokemua/0100.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(17, 61), new PokemuaTemplate.SkillEntry(22, 57), new PokemuaTemplate.SkillEntry(36, 31), new PokemuaTemplate.SkillEntry(43, 58)}),
            new PokemuaTemplate(101, "Electrode", 60, 50, 70, "file:asset/pokemua/0101.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 61), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(17, 61), new PokemuaTemplate.SkillEntry(22, 57), new PokemuaTemplate.SkillEntry(40, 31), new PokemuaTemplate.SkillEntry(50, 58)}),
            new PokemuaTemplate(102, "Exeggcute", 60, 40, 80, "file:asset/pokemua/0102.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 75), new PokemuaTemplate.SkillEntry(42, 3)}),
            new PokemuaTemplate(103, "Exeggutor", 95, 95, 85, "file:asset/pokemua/0103.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 75), new PokemuaTemplate.SkillEntry(28, 59)}),
            new PokemuaTemplate(104, "Cubone", 50, 50, 95, "file:asset/pokemua/0104.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 76), new PokemuaTemplate.SkillEntry(38, 38), new PokemuaTemplate.SkillEntry(43, 77), new PokemuaTemplate.SkillEntry(46, 6)}),
            new PokemuaTemplate(105, "Marowak", 60, 80, 110, "file:asset/pokemua/0105.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 76), new PokemuaTemplate.SkillEntry(41, 38), new PokemuaTemplate.SkillEntry(48, 77), new PokemuaTemplate.SkillEntry(55, 6)}),
            new PokemuaTemplate(106, "Hitmonlee", 50, 120, 53, "file:asset/pokemua/0106.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 34), new PokemuaTemplate.SkillEntry(33, 78), new PokemuaTemplate.SkillEntry(38, 79), new PokemuaTemplate.SkillEntry(48, 80), new PokemuaTemplate.SkillEntry(53, 81)}),
            new PokemuaTemplate(107, "Hitmonchan", 50, 105, 79, "file:asset/pokemua/0107.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 82), new PokemuaTemplate.SkillEntry(33, 83), new PokemuaTemplate.SkillEntry(38, 84), new PokemuaTemplate.SkillEntry(43, 85), new PokemuaTemplate.SkillEntry(48, 86), new PokemuaTemplate.SkillEntry(53, 87)}),
            new PokemuaTemplate(108, "Lickitung", 90, 55, 75, "file:asset/pokemua/0108.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 28), new PokemuaTemplate.SkillEntry(7, 59), new PokemuaTemplate.SkillEntry(31, 54)}),
            new PokemuaTemplate(109, "Koffing", 40, 65, 95, "file:asset/pokemua/0109.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 88), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(32, 65), new PokemuaTemplate.SkillEntry(40, 57), new PokemuaTemplate.SkillEntry(48, 58)}),
            new PokemuaTemplate(110, "Weezing", 65, 90, 120, "file:asset/pokemua/0110.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 65), new PokemuaTemplate.SkillEntry(1, 88), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(32, 65), new PokemuaTemplate.SkillEntry(43, 57), new PokemuaTemplate.SkillEntry(53, 58)}),
            new PokemuaTemplate(111, "Rhyhorn", 80, 85, 95, "file:asset/pokemua/0111.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 36), new PokemuaTemplate.SkillEntry(30, 59), new PokemuaTemplate.SkillEntry(40, 18), new PokemuaTemplate.SkillEntry(45, 37), new PokemuaTemplate.SkillEntry(55, 51)}),
            new PokemuaTemplate(112, "Rhydon", 105, 130, 120, "file:asset/pokemua/0112.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 18), new PokemuaTemplate.SkillEntry(1, 36), new PokemuaTemplate.SkillEntry(1, 59), new PokemuaTemplate.SkillEntry(30, 59), new PokemuaTemplate.SkillEntry(40, 18), new PokemuaTemplate.SkillEntry(48, 37), new PokemuaTemplate.SkillEntry(64, 51)}),
            new PokemuaTemplate(113, "Chansey", 250, 5, 5, "file:asset/pokemua/0113.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 40), new PokemuaTemplate.SkillEntry(1, 39), new PokemuaTemplate.SkillEntry(54, 41)}),
            new PokemuaTemplate(114, "Tangela", 65, 55, 115, "file:asset/pokemua/0114.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 71), new PokemuaTemplate.SkillEntry(1, 55), new PokemuaTemplate.SkillEntry(29, 43), new PokemuaTemplate.SkillEntry(45, 54)}),
            new PokemuaTemplate(115, "Kangaskhan", 105, 95, 80, "file:asset/pokemua/0115.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 82), new PokemuaTemplate.SkillEntry(1, 6), new PokemuaTemplate.SkillEntry(26, 12), new PokemuaTemplate.SkillEntry(36, 86), new PokemuaTemplate.SkillEntry(46, 89)}),
            new PokemuaTemplate(116, "Horsea", 30, 40, 70, "file:asset/pokemua/0116.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 10), new PokemuaTemplate.SkillEntry(30, 11), new PokemuaTemplate.SkillEntry(45, 14)}),
            new PokemuaTemplate(117, "Seadra", 55, 65, 95, "file:asset/pokemua/0117.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 10), new PokemuaTemplate.SkillEntry(30, 11), new PokemuaTemplate.SkillEntry(52, 14)}),
            new PokemuaTemplate(118, "Goldeen", 45, 67, 60, "file:asset/pokemua/0118.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 26), new PokemuaTemplate.SkillEntry(24, 36), new PokemuaTemplate.SkillEntry(30, 18), new PokemuaTemplate.SkillEntry(37, 90), new PokemuaTemplate.SkillEntry(45, 37)}),
            new PokemuaTemplate(119, "Seaking", 80, 92, 65, "file:asset/pokemua/0119.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 26), new PokemuaTemplate.SkillEntry(24, 36), new PokemuaTemplate.SkillEntry(30, 18), new PokemuaTemplate.SkillEntry(39, 90), new PokemuaTemplate.SkillEntry(48, 37)}),
            new PokemuaTemplate(120, "Staryu", 30, 45, 55, "file:asset/pokemua/0120.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(17, 11), new PokemuaTemplate.SkillEntry(32, 31), new PokemuaTemplate.SkillEntry(47, 14)}),
            new PokemuaTemplate(121, "Starmie", 60, 75, 85, "file:asset/pokemua/0121.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(1, 11)}),
            new PokemuaTemplate(122, "Mr. Mime", 40, 45, 65, "file:asset/pokemua/0122.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 15), new PokemuaTemplate.SkillEntry(15, 15), new PokemuaTemplate.SkillEntry(31, 40)}),
            new PokemuaTemplate(123, "Scyther", 70, 110, 80, "file:asset/pokemua/0123.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 22), new PokemuaTemplate.SkillEntry(29, 7)}),
            new PokemuaTemplate(124, "Jynx", 65, 50, 35, "file:asset/pokemua/0124.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 39), new PokemuaTemplate.SkillEntry(18, 68), new PokemuaTemplate.SkillEntry(23, 40), new PokemuaTemplate.SkillEntry(31, 84), new PokemuaTemplate.SkillEntry(39, 35), new PokemuaTemplate.SkillEntry(47, 38), new PokemuaTemplate.SkillEntry(58, 91)}),
            new PokemuaTemplate(125, "Electabuzz", 65, 83, 57, "file:asset/pokemua/0125.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 22), new PokemuaTemplate.SkillEntry(34, 30), new PokemuaTemplate.SkillEntry(42, 85), new PokemuaTemplate.SkillEntry(54, 32)}),
            new PokemuaTemplate(126, "Magmar", 65, 95, 57, "file:asset/pokemua/0126.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 5), new PokemuaTemplate.SkillEntry(43, 83), new PokemuaTemplate.SkillEntry(52, 88), new PokemuaTemplate.SkillEntry(55, 8)}),
            new PokemuaTemplate(127, "Pinsir", 65, 125, 100, "file:asset/pokemua/0127.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 72), new PokemuaTemplate.SkillEntry(25, 50), new PokemuaTemplate.SkillEntry(30, 73), new PokemuaTemplate.SkillEntry(49, 7)}),
            new PokemuaTemplate(128, "Tauros", 75, 100, 95, "file:asset/pokemua/0128.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(21, 59), new PokemuaTemplate.SkillEntry(44, 6), new PokemuaTemplate.SkillEntry(51, 51)}),
            new PokemuaTemplate(129, "Magikarp", 20, 10, 55, "file:asset/pokemua/0129.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(15, 0)}),
            new PokemuaTemplate(130, "Gyarados", 95, 125, 79, "file:asset/pokemua/0130.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 12), new PokemuaTemplate.SkillEntry(1, 92), new PokemuaTemplate.SkillEntry(1, 14), new PokemuaTemplate.SkillEntry(20, 12), new PokemuaTemplate.SkillEntry(25, 92), new PokemuaTemplate.SkillEntry(41, 14), new PokemuaTemplate.SkillEntry(52, 93)}),
            new PokemuaTemplate(131, "Lapras", 130, 85, 80, "file:asset/pokemua/0131.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 11), new PokemuaTemplate.SkillEntry(25, 35), new PokemuaTemplate.SkillEntry(38, 64), new PokemuaTemplate.SkillEntry(46, 14)}),
            new PokemuaTemplate(132, "Ditto", 48, 48, 48, "file:asset/pokemua/0132.png", new PokemuaTemplate.SkillEntry[]{}),
            new PokemuaTemplate(133, "Eevee", 55, 55, 50, "file:asset/pokemua/0133.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(27, 22), new PokemuaTemplate.SkillEntry(37, 12), new PokemuaTemplate.SkillEntry(45, 51)}),
            new PokemuaTemplate(134, "Vaporeon", 130, 65, 60, "file:asset/pokemua/0134.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 22), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(1, 11), new PokemuaTemplate.SkillEntry(27, 22), new PokemuaTemplate.SkillEntry(31, 11), new PokemuaTemplate.SkillEntry(40, 12), new PokemuaTemplate.SkillEntry(54, 14)}),
            new PokemuaTemplate(135, "Jolteon", 65, 65, 60, "file:asset/pokemua/0135.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 22), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(1, 30), new PokemuaTemplate.SkillEntry(27, 22), new PokemuaTemplate.SkillEntry(31, 30), new PokemuaTemplate.SkillEntry(42, 34), new PokemuaTemplate.SkillEntry(48, 20), new PokemuaTemplate.SkillEntry(54, 32)}),
            new PokemuaTemplate(136, "Flareon", 65, 130, 60, "file:asset/pokemua/0136.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 5), new PokemuaTemplate.SkillEntry(1, 22), new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(27, 22), new PokemuaTemplate.SkillEntry(31, 5), new PokemuaTemplate.SkillEntry(40, 12), new PokemuaTemplate.SkillEntry(44, 9), new PokemuaTemplate.SkillEntry(48, 6), new PokemuaTemplate.SkillEntry(54, 8)}),
            new PokemuaTemplate(137, "Porygon", 65, 60, 70, "file:asset/pokemua/0137.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 0), new PokemuaTemplate.SkillEntry(23, 16), new PokemuaTemplate.SkillEntry(42, 62)}),
            new PokemuaTemplate(138, "Omanyte", 35, 40, 100, "file:asset/pokemua/0138.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 11), new PokemuaTemplate.SkillEntry(34, 36), new PokemuaTemplate.SkillEntry(46, 67), new PokemuaTemplate.SkillEntry(53, 14)}),
            new PokemuaTemplate(139, "Omastar", 70, 60, 125, "file:asset/pokemua/0139.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 36), new PokemuaTemplate.SkillEntry(1, 11), new PokemuaTemplate.SkillEntry(34, 36), new PokemuaTemplate.SkillEntry(44, 67), new PokemuaTemplate.SkillEntry(49, 14)}),
            new PokemuaTemplate(140, "Kabuto", 30, 80, 90, "file:asset/pokemua/0140.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(34, 43), new PokemuaTemplate.SkillEntry(39, 7), new PokemuaTemplate.SkillEntry(49, 14)}),
            new PokemuaTemplate(141, "Kabutops", 60, 115, 105, "file:asset/pokemua/0141.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 43), new PokemuaTemplate.SkillEntry(1, 4), new PokemuaTemplate.SkillEntry(34, 43), new PokemuaTemplate.SkillEntry(39, 7), new PokemuaTemplate.SkillEntry(53, 14)}),
            new PokemuaTemplate(142, "Aerodactyl", 80, 105, 65, "file:asset/pokemua/0142.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 23), new PokemuaTemplate.SkillEntry(38, 12), new PokemuaTemplate.SkillEntry(45, 51), new PokemuaTemplate.SkillEntry(54, 93)}),
            new PokemuaTemplate(143, "Snorlax", 160, 110, 65, "file:asset/pokemua/0143.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 60), new PokemuaTemplate.SkillEntry(35, 35), new PokemuaTemplate.SkillEntry(48, 41), new PokemuaTemplate.SkillEntry(56, 93)}),
            new PokemuaTemplate(144, "Articuno", 90, 85, 100, "file:asset/pokemua/0144.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 64), new PokemuaTemplate.SkillEntry(1, 26), new PokemuaTemplate.SkillEntry(51, 91)}),
            new PokemuaTemplate(145, "Zapdos", 90, 90, 85, "file:asset/pokemua/0145.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 27), new PokemuaTemplate.SkillEntry(1, 30), new PokemuaTemplate.SkillEntry(51, 32)}),
            new PokemuaTemplate(146, "Moltres", 90, 100, 90, "file:asset/pokemua/0146.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 9), new PokemuaTemplate.SkillEntry(1, 26), new PokemuaTemplate.SkillEntry(60, 94)}),
            new PokemuaTemplate(147, "Dratini", 41, 64, 45, "file:asset/pokemua/0147.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 28), new PokemuaTemplate.SkillEntry(30, 54), new PokemuaTemplate.SkillEntry(40, 92), new PokemuaTemplate.SkillEntry(50, 93)}),
            new PokemuaTemplate(148, "Dragonair", 61, 84, 65, "file:asset/pokemua/0148.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 28), new PokemuaTemplate.SkillEntry(35, 54), new PokemuaTemplate.SkillEntry(45, 92), new PokemuaTemplate.SkillEntry(55, 93)}),
            new PokemuaTemplate(149, "Dragonite", 91, 134, 95, "file:asset/pokemua/0149.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 28), new PokemuaTemplate.SkillEntry(35, 54), new PokemuaTemplate.SkillEntry(45, 92), new PokemuaTemplate.SkillEntry(60, 93)}),
            new PokemuaTemplate(150, "Mewtwo", 106, 110, 90, "file:asset/pokemua/0150.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 15), new PokemuaTemplate.SkillEntry(1, 45), new PokemuaTemplate.SkillEntry(1, 31), new PokemuaTemplate.SkillEntry(66, 45)}),
            new PokemuaTemplate(151, "Mew", 100, 100, 100, "file:asset/pokemua/0151.png", new PokemuaTemplate.SkillEntry[]{new PokemuaTemplate.SkillEntry(1, 39), new PokemuaTemplate.SkillEntry(20, 86), new PokemuaTemplate.SkillEntry(40, 45)})
    };

    /**
     * Load a Pokemua from the template
     */
    public static PokemuaTemplate load(int index) {
        return pokemuasData[index];
    }

    /**
     * Load a Pokemua from the template and set index and level
     */
    public static Pokemua load(int index, int level) {
        PokemuaTemplate template = PokemuaLoader.load(index);
        Pokemua pokemua = new Pokemua(template, level);

        ArrayList<SkillTemplate> possibleSkill = new ArrayList<>();

        for (PokemuaTemplate.SkillEntry skillEntry : template.getSkillEntries()) {
            if (skillEntry.accquireLevel <= level) {
                possibleSkill.add(skillEntry.getTemplate());
            }
        }

        while (possibleSkill.size() > 0 && pokemua.getSkills().size() < 4) {
            int skillIdx = (int) Math.random() * possibleSkill.size();
            SkillTemplate skillTemplate = possibleSkill.remove(skillIdx);
            Skill addedSkill = skillTemplate.toSkill(pokemua);
            pokemua.learnSkill(addedSkill);
        }

        return pokemua;
    }

    /**
     * Get a skill from a Pokemua
     */
    public static SkillTemplate getSkill(int id, int level) {
        PokemuaTemplate template = PokemuaLoader.load(id);
        for (PokemuaTemplate.SkillEntry skillEntry : template.getSkillEntries()) {
            if (skillEntry.getAccquireLevel() == level) {
                return skillEntry.getTemplate();
            }
        }
        return null;
    }
}
